"use client";
import { useState } from "react";
import { Award, Bell, Check, ChevronRight, FileCheck2, Medal, Moon, Search, Sparkles, Star, Sun, TrendingUp, Trophy, Users } from "lucide-react";
import "./design-preview.css";
const leaders=[["Nguyễn Minh Anh","Chi đoàn 21DTH1","980","MA"],["Trần Quốc Huy","CLB Lập trình","945","QH"],["Lê Hoàng Yến","Chi đoàn 22DTH2","910","HY"],["Phạm Gia Bảo","Chi đoàn 21DTH3","875","GB"]];
const steps=[["Thông tin hồ sơ","Đã hoàn tất","done"],["Minh chứng","12 tệp đã tải lên","done"],["Xét duyệt cấp Khoa","Đang xử lý","active"],["Công bố kết quả","Dự kiến 28/07",""]];
export default function DesignPreviewPage(){const[dark,setDark]=useState(true);return <main className={`award-preview ${dark?"is-dark":"is-light"}`}><div className="award-orb orb-one"/><div className="award-orb orb-two"/>
<header className="award-header"><a className="award-brand" href="#award-dashboard"><span><Star size={21} fill="currentColor"/></span><p><strong>DNTU Awards</strong><small>University Commendation</small></p></a><nav><a className="active" href="#award-dashboard">Tổng quan</a><a href="#leaderboard">Xếp hạng</a><a href="#certificate">Chứng nhận</a></nav><div className="award-actions"><button aria-label="Tìm kiếm"><Search/></button><button aria-label="Thông báo"><Bell/></button><button className="theme-toggle" aria-label={dark?"Chuyển sang giao diện sáng":"Chuyển sang giao diện tối"} onClick={()=>setDark(!dark)}><Sun/><i/><Moon/></button><span className="award-avatar">NH</span></div></header>
<section className="award-content" id="award-dashboard"><div className="award-welcome"><div><span className="kicker"><Sparkles/> HỌC KỲ II · 2025–2026</span><h1>Vinh danh hành trình<br/><em>tạo nên khác biệt.</em></h1><p>Theo dõi thành tích, hồ sơ xét duyệt và những gương mặt nổi bật trong cộng đồng sinh viên DNTU.</p></div><button className="primary">Nộp hồ sơ mới <ChevronRight/></button></div>
<div className="award-bento"><article className="award-card overview"><header><div><span>TỔNG QUAN THÀNH TÍCH</span><h2>Dấu ấn của bạn</h2></div><button>Năm học 2025–2026</button></header><div className="stat-row"><div><i className="blue"><Trophy/></i><p><strong>12</strong><small>Danh hiệu</small></p><b>+3 năm nay</b></div><div><i className="gold"><Medal/></i><p><strong>08</strong><small>Chứng nhận</small></p><b>Top 5%</b></div><div><i className="violet"><TrendingUp/></i><p><strong>980</strong><small>Điểm thi đua</small></p><b>+12.4%</b></div></div><div className="award-chart">{[42,56,49,68,76,92,82,100,91,112,108,128].map((h,i)=><i key={i} style={{height:h}}/>)}<span>Tháng 1</span><span>Tháng 3</span><span>Tháng 6</span><span>Tháng 9</span><span>Tháng 12</span></div></article>
<article className="award-card medal-card"><div className="medal-scene"><span className="clay-star one"><Star fill="currentColor"/></span><span className="clay-star two"><Star fill="currentColor"/></span><div className="ribbon"/><div className="medal"><Award/></div></div><span className="kicker">THÀNH TỰU NỔI BẬT</span><h2>Sinh viên 5 tốt</h2><p>Cấp Trường · Năm học 2024–2025</p><button>Xem thành tích <ChevronRight/></button></article>
<article className="award-card leaderboard" id="leaderboard"><header><div><span>BẢNG XẾP HẠNG</span><h2>Gương mặt dẫn đầu</h2></div><b className="live"><i/> Trực tiếp</b></header><div className="leader-list">{leaders.map((l,i)=><div key={l[0]} className={i===0?"first":""}><strong className={`rank r${i+1}`}>{i+1}</strong><span className="person-avatar">{l[3]}</span><p><b>{l[0]}</b><small>{l[1]}</small></p><span className="score">{l[2]}<small>điểm</small></span></div>)}</div><button className="text-button">Xem toàn bộ bảng xếp hạng <ChevronRight/></button></article>
<article className="award-card progress-card"><header><div><span>HỒ SƠ #HS-2025-084</span><h2>Tiến độ xét duyệt</h2></div><b className="review-badge">Đang xét duyệt</b></header><div className="progress-list">{steps.map((s,i)=><div key={s[0]} className={s[2]}><span>{s[2]==="done"?<Check/>:i+1}</span><p><b>{s[0]}</b><small>{s[1]}</small></p></div>)}</div><footer><FileCheck2/><p><b>Hồ sơ đã được tiếp nhận</b><small>Hội đồng đang xác minh minh chứng của bạn.</small></p></footer></article>
<article className="award-card certificate-card" id="certificate"><header><div><span>CHỨNG NHẬN SỐ</span><h2>Thành tích mới nhất</h2></div><button><ChevronRight/></button></header><div className="certificate"><div className="cert-logo"><Star fill="currentColor"/></div><small>TRƯỜNG ĐẠI HỌC CÔNG NGHỆ ĐỒNG NAI</small><h3>GIẤY CHỨNG NHẬN</h3><p>Chứng nhận sinh viên</p><strong>NGUYỄN MINH ANH</strong><p>Đạt danh hiệu <b>Thanh niên tiên tiến làm theo lời Bác</b></p><footer><span>TM. BAN THƯỜNG VỤ</span><i><Award/></i><span>Ngày 18 tháng 05 năm 2026</span></footer></div><div className="cert-meta"><span><FileCheck2/> Đã xác thực Blockchain</span><button>Tải chứng nhận</button></div></article>
<article className="award-card community"><span><Users/></span><p><strong>2,480+</strong><small>Sinh viên tham gia</small></p><i>+18%</i></article></div></section></main>}
