"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Trash2, TriangleAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
export function DeleteApplicationButton({ id, code, subjectName, status, compact = false }: { id: string; code: string; subjectName: string; status: string; compact?: boolean }) {
  const router = useRouter(); const [open,setOpen]=useState(false); const [confirmationCode,setConfirmationCode]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const needsCode=status!=="draft";
  async function remove(){setBusy(true);setError("");const response=await fetch(`/api/applications/${id}`,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({confirmationCode})});const data=await response.json();setBusy(false);if(!response.ok){setError(data.error||"Không thể xóa hồ sơ");return;}setOpen(false);router.push("/applications");router.refresh();}
  return <><Button size="sm" variant="danger" onClick={()=>setOpen(true)} aria-label={`Xóa hồ sơ ${code}`}><Trash2 size={14}/>{compact?"":"Xóa hồ sơ"}</Button>{open&&<div className="danger-dialog-backdrop" role="presentation" onMouseDown={(event)=>{if(event.currentTarget===event.target&&!busy)setOpen(false);}}><div className="danger-dialog" role="alertdialog" aria-modal="true" aria-labelledby={`delete-app-${id}`}><span className="danger-dialog-icon"><TriangleAlert size={25}/></span><h2 id={`delete-app-${id}`}>Xóa hồ sơ vĩnh viễn?</h2><p><strong>{subjectName}</strong> · {code}</p><p>Hoạt động, khen thưởng, lịch sử xét duyệt và toàn bộ ảnh minh chứng sẽ bị xóa. Không thể hoàn tác.</p>{needsCode&&<label className="field"><span className="field-label">Nhập mã <strong>{code}</strong> để xác nhận</span><input className="input" value={confirmationCode} onChange={(e)=>setConfirmationCode(e.target.value)} autoFocus/></label>}{error&&<div className="notice notice-error">{error}</div>}<div className="danger-dialog-actions"><Button variant="outline" disabled={busy} onClick={()=>setOpen(false)}>Hủy</Button><Button variant="danger" loading={busy} disabled={needsCode&&confirmationCode!==code} onClick={remove}>Xóa vĩnh viễn</Button></div></div></div>}</>;
}
