import type { ApplicationStatus } from "@/lib/constants";
export type UserRole = "admin" | "reviewer" | "submitter";
export type CollectiveType = "branch" | "club";
export type PeriodStatus = "draft" | "open" | "closed";
export type SubmissionScope = "individual" | "branch" | "club";
export type Profile = {
    id: string;
    email: string;
    full_name: string;
    role: UserRole;
    submission_scope: SubmissionScope;
    branch_code: string | null;
    club_id: string | null;
    is_active: boolean;
    must_change_password: boolean;
};
export type Branch = {
    code: string;
    name: string;
    is_active: boolean;
};
export type Club = {
    id: string;
    code: string;
    name: string;
    is_active: boolean;
    created_at?: string;
    updated_at?: string;
};
export type EvaluationPeriod = {
    id: string;
    name: string;
    description: string | null;
    starts_at: string;
    ends_at: string;
    status: PeriodStatus;
    allow_individual: boolean;
    allow_branch_collective: boolean;
    allow_club_collective: boolean;
    created_at?: string;
    updated_at?: string;
};
export type Evidence = {
    id: string;
    file_name: string;
    mime_type: string;
    size_bytes: number;
    category: string;
    parent_type: string;
    parent_id: string;
    created_at: string;
    public_token: string;
    public_view_enabled: boolean;
};
export type Activity = {
    id: string;
    client_key: string;
    level: "faculty" | "university";
    name: string;
    organizer: string | null;
    activity_date: string | null;
    role: string | null;
    result: string | null;
    contribution: string | null;
    evidences?: Evidence[];
};
export type PriorAward = {
    id: string;
    client_key: string;
    award_type: "certificate" | "commendation";
    title: string;
    decision_number: string;
    issued_date: string | null;
    issuer: string;
    evidences?: Evidence[];
};
export type Application = {
    id: string;
    code: string;
    evaluation_period_id: string;
    period_name?: string;
    application_type: "individual" | "collective";
    collective_type: CollectiveType | null;
    branch_code: string | null;
    club_id: string | null;
    club_name?: string | null;
    subject_name: string;
    student_id: string | null;
    birth_date: string | null;
    position: string | null;
    phone: string | null;
    email: string | null;
    achievements: string;
    role_contribution: string | null;
    targets_result: string | null;
    initiatives: string | null;
    impact: string | null;
    summary: string | null;
    status: ApplicationStatus;
    review_comment: string | null;
    created_by: string;
    reviewer_id: string | null;
    created_at: string;
    updated_at: string;
    submitted_at: string | null;
    decided_at: string | null;
    activities?: Activity[];
    prior_awards?: PriorAward[];
    evidences?: Evidence[];
};
export type UnitAccountSummary = {
    id: string;
    email: string;
    full_name: string;
    submission_scope: Extract<SubmissionScope, "branch" | "club">;
    branch_code: string | null;
    club_id: string | null;
    is_active: boolean;
    must_change_password: boolean;
};

